# Generated by Django 5.0.6 on 2024-06-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0002_alter_pump_options_alter_refuel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refuel',
            options={'ordering': ['-refuel_date'], 'verbose_name': 'Abastecimento', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AlterField(
            model_name='refuel',
            name='refuel_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Abastecimento'),
        ),
    ]
