# Generated by Django 5.0.6 on 2024-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0004_alter_pump_id_alter_refuel_id_alter_tank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='amount',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='liters',
            field=models.FloatField(verbose_name='Litros'),
        ),
    ]
