# Generated by Django 5.0.6 on 2024-06-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0005_alter_refuel_amount_alter_refuel_liters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={},
        ),
        migrations.AlterField(
            model_name='refuel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa'),
        ),
    ]
